### ISSUE TITLE
Notifications in Voctogui

### ISSUE THREAD

**Issue by v0tti** [voc/voctomix#156] opened 2017-09-09 00:44 UTC
The GUI should be able to show some kind of notifications (like the stream pause/blank notifications). Those could be triggered via IRC (if the name of the room is mentioned) or via a http/rest API.
In this way the Voctomix operator can be alerted to look at the chat or do certain actions.

An advancement of this feature could be the remote control of Voctomix via IRC e.g. set the stream blanker via an specific command, in this case access to the IRC-Channel should be restricted.

**Comment by derpeter** [comment] 2017-09-11 08:29
I like the idea. We could also think of adding a hole chat and maybe intercom feature top the gui. This would be more screen space efficient than putting the chat below. 

Not sure if this fits here but i would also like to add the intercom (either mumble or SIP based) to the GUI.

**Comment by MaZderMind** [comment] 2017-09-11 09:37
This is a duplicate of #93.

Implementing a custom Chat would be another Story. @derpeter please open one some explanations about the benefits above the current solution.

**Closed by MaZderMind** 2017-09-11 09:37 UTC
Labels: enhancement, voctogui
