### ISSUE TITLE
Space key switches to live if transition is not available.

### ISSUE THREAD

**Issue by vale** [voc/voctomix#304] opened 2023-12-26 22:05 UTC
When trying to switch between two scenes which do not have a transition available the space key does not transition between scenes but switches the stream from break to live.

To reproduce
1. Set cam1 and slides in lecture mode select cam2 fullscreen as preview. (or otherway around)
2. Press space key.

**Comment by jbeyerstedt** [comment] 2024-03-21 10:58
Duplicate of #275

**Comment by Kunsi** [comment] 2024-05-19 12:11
fixed in #320

**Closed by Kunsi** 2024-05-19 12:11 UTC
Labels: bug
