### ISSUE TITLE
Show recording status in voctogui

### ISSUE THREAD

**Issue by derpeter** [voc/voctomix#84] opened 2016-08-09 10:09 UTC
As recording is the most important part we should monitor the recording and give the gui operator feedback on it. Maybe we should also send the amount of free HDD space to the UI. 
This would give the operator the chance to e.g. interrupt the talk until the problem is fixed or at least call for help.

sending the discspace is easy, checking the recording is  not that easy we need to think about what we use to determin if its running (process id / growing file size / nifty ffprobe commands)

**Comment by derpeter** [comment] 2016-08-09 10:10
This could also be extendet to show vocto-staus infos in the UI

**Comment by MaZderMind** [comment] 2016-08-12 20:47
duplicate of #44

**Closed by MaZderMind** 2016-08-12 20:47 UTC
Labels: enhancement, voctogui
