### ISSUE TITLE
Clipping alert

### ISSUE THREAD

**Issue by CarlFK** [voc/voctomix#164] opened 2017-10-06 16:08 UTC
When the audio level exceeds some threshold, something should happen.

I would like voctogui to react - like change the window background to red.  
add a "reset alarm" button.  
maybe the alarm button flashes red.

A local beep might be good too.   or tick, or buzz.   or ring someone's phone.  only 1/2 kidding.

If the server advertised this like Cut event (how is this called?), I can imagine logging and using that data in post, both to fix one video and to do analysis.  At the end of the first day, if one room has enough alerts, go have a look at that room's equipment.    I kinda do this with a visualization of the audio (a whole day can fit on a screen) but it is cpu intensive that competes with encoding videos.

**Comment by MaZderMind** [comment] 2018-05-29 19:32
duplicate of #76

**Closed by MaZderMind** 2018-05-29 19:32 UTC
Labels: enhancement
